# Generated by Django 3.2.25 on 2025-09-03 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('goal_type', models.CharField(choices=[('binary', 'Бинарный'), ('numeric', 'Числовой')], default='binary', max_length=10, verbose_name='Тип цели')),
                ('goal_value', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цель (число)')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно')], default='daily', max_length=10, verbose_name='Частота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateField(verbose_name='Дата выполнения')),
                ('value', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Значение')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main.habit')),
            ],
            options={
                'verbose_name': 'Запись выполнения',
                'verbose_name_plural': 'Записи выполнения',
                'ordering': ['-completed_at'],
                'unique_together': {('habit', 'completed_at')},
            },
        ),
    ]
